### ISSUE TITLE
Add Python version and environment info to README

### ISSUE THREAD

**Issue by elisagdelope** [HySonLab/Protein_Pretrain#1]
Hi, this looks like an interesting project!

For the sake of reproducibility, it would be beneficial if you could add some information about the Python version and environment setup to the README. This would help users to set up their environments correctly and avoid potential issues related to version incompatibilities.

Specifically, it would be great if you could include:
- The Python version used for development and testing.
- A requirements.txt file or similar (e.g., environment.yml for Conda) that lists all the dependencies required to run the project.
This additional information would make it easier for others to replicate your results and contribute to the project.

**Comment by thanhduy1842001** [comment]
Thank you for your interest in our research and your valuable suggestion. I have included the Python version used, along with an environment.yml file for Conda in the repository. Additionally, an "Environment Setup" guide has been incorporated into the README to ensure easy reproducibility.
